name: fconfigproxy
description: "A Flutter package for configuring proxy with annotation support and code generation."
version: 0.0.2
homepage: https://github.com/1006033520/fconfigproxy_flutter

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'


dependencies:
  analyzer: ^8.1.1
  meta: ^1.9.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  collection: ^1.18.0
  source_gen: ^4.0.1
  jinja: ^0.6.4
  build: ^4.0.0


dev_dependencies:
  build_runner: ^2.8.0


  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
