name: fconfigproxy_hive_storage
description: "A Flutter plugin for storing configuration data using Hive database."
version: 0.0.1
homepage: https://github.com/1006033520/fconfigproxy_flutter

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fconfigproxy:
    path: ../../
